In [3]:
import glob, os

file_list = glob.glob('/ZFS4T/opensrl/thchs30/data_thchs30/data/*.wav')
dit = {}
for pth in file_list:
    basename = os.path.basename(pth)
    spk_name, seq = basename.split('.wav')[0].split('_')
    if spk_name not in dit:
        dit[spk_name] = []
    dit[spk_name].append(pth)
print(len(dit))
for spk_name, val in dit.items():
    print('%s : %d'%(spk_name, len(val))) 

60
A23 : 250
C12 : 250
C22 : 250
A7 : 249
C14 : 250
B6 : 248
B11 : 250
A11 : 250
C17 : 250
C18 : 250
C19 : 250
B22 : 250
C20 : 250
C31 : 250
B8 : 250
A2 : 249
B4 : 250
A36 : 250
D21 : 250
C6 : 250
A34 : 249
A14 : 250
D7 : 249
C13 : 250
D8 : 250
C4 : 250
B7 : 249
D6 : 250
D31 : 250
B33 : 250
A33 : 110
D13 : 250
A6 : 250
D32 : 249
D11 : 249
A19 : 250
A12 : 150
D4 : 250
B12 : 250
A8 : 250
B31 : 250
B15 : 250
B2 : 249
A22 : 250
C23 : 250
B32 : 250
C7 : 249
A4 : 250
C2 : 90
D12 : 248
C21 : 250
C8 : 250
A13 : 250
A32 : 250
C32 : 250
B21 : 19
A9 : 13
A5 : 5
B34 : 7
A35 : 7


In [6]:
import os
import soundfile as sf

print(os.path.getsize('/ZFS4T/opensrl/aishell1_part/S0176/BAC009S0176W0317.wav'))
wav = sf.read('/ZFS4T/opensrl/aishell1_part/S0176/BAC009S0176W0317.wav')[0]
print(len(wav) * 2 + 44)

109036
109036


In [7]:
for i in range(10, 0, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [8]:
import torch

g  = torch.Generator()
g.manual_seed(11)

print(torch.randperm(10, generator = g))

tensor([1, 7, 2, 0, 9, 3, 5, 6, 4, 8])


In [14]:
import torch

print(torch.tril(torch.ones(4, 4)).unsqueeze(0).unsqueeze(0).shape)

torch.Size([1, 1, 4, 4])


In [15]:
import torch

print(torch.arange(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
import torch

def sequence_mask(length, max_length=None):
    if max_length is None:
        max_length = length.max()
    x = torch.arange(max_length, dtype=length.dtype, device=length.device)
    return x.unsqueeze(0) < length.unsqueeze(1)

length = torch.Tensor([3, 4, 2])
max_length = 4
print(sequence_mask(length, max_length))


tensor([[ True,  True,  True, False],
        [ True,  True,  True,  True],
        [ True,  True, False, False]])


In [6]:
print('%.2f%%'%(3.444))

3.44%


In [15]:
with open('../symbol_to_id.json', 'r') as f:
    for line in reversed(f.readlines()):
        print(u'%s'%(line.rstrip()))

}
    "\uff50": 190
    "\uff42": 189,
    "\uff1f": 188,
    "\uff0c": 187,
    "\uff01": 186,
    "\u3002": 185,
    "zh": 184,
    "z": 183,
    "y": 182,
    "x": 181,
    "w": 180,
    "v\u00e80": 179,
    "v4": 178,
    "v3": 177,
    "v2": 176,
    "uo4": 175,
    "uo3": 174,
    "uo2": 173,
    "uo1": 172,
    "uo": 171,
    "un4": 170,
    "un3": 169,
    "un2": 168,
    "un1": 167,
    "un": 166,
    "ui4": 165,
    "ui3": 164,
    "ui2": 163,
    "ui1": 162,
    "ue4": 161,
    "ue3": 160,
    "ue2": 159,
    "ue1": 158,
    "uang4": 157,
    "uang3": 156,
    "uang2": 155,
    "uang1": 154,
    "uang": 153,
    "uan4": 152,
    "uan3": 151,
    "uan2": 150,
    "uan1": 149,
    "uan": 148,
    "uai4": 147,
    "uai3": 146,
    "uai2": 145,
    "uai1": 144,
    "uai": 143,
    "ua4": 142,
    "ua3": 141,
    "ua2": 140,
    "ua1": 139,
    "ua": 138,
    "u4": 137,
    "u3": 136,
    "u2": 135,
    "u1": 134,
    "u": 133,
    "t": 132,
    "sh": 131,
    "s": 130,
    "r": 

In [17]:
import torch

a = torch.load('/ZFS4T/opensrl/aishell1_part/S0710/BAC009S0710W0188.spec.pt')

In [3]:
import glob, os
f_list = glob.glob(os.path.join('/ZFS4T/tts/data/VITS/model_saved/', 'G_*.pth'))
f_list.sort(key=lambda f: int("".join(filter(str.isdigit, f))))
x = f_list[-1]
print(x)

/ZFS4T/tts/data/VITS/model_saved/G_4000.pth


In [ ]:
lst = [
    '/mnt/disk3/huangyao/tts/vits/filelists/magicdata_audio_sid_train.16000.cleaned.txt',
    '/mnt/disk3/huangyao/tts/vits/filelists/magicdata_audio_sid_valid.16000.cleaned.txt'
]

dit = {}
idx = 0
for filepth in lst:
    with open(filepth, 'r') as f:
        for line in f.readlines():
            for p in line.rstrip().split('|')[-1].split():
                if p not in dit:
                    dit[p] = idx
                    idx += 1

print(dit)

In [3]:
import torch

a = torch.nn.Embedding(6, 256)(torch.LongTensor([1, 2, 3]))
print(a.shape)

torch.Size([3, 256])
